const data = [
    {
        "id": 2,
        "title": "مازونيت 200 م نص مفروش للإيجار في هايد بارك",
        "image": "https://img-1.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cf56c0ebd3127537128.jpg",
        "rooms": "3",
        "bathrooms": "4",
        "size": "200 متر²",
        "price": "65,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / سنتر فيل - كمبوند هايد بارك",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650727-for-rent-cairo-new-cairo-compounds-hyde-park-centre-ville-hyde-park/",
        "originalAdID": null
    },
    {
        "id": 3,
        "title": "شقة 160م للايجار مفروش فى سيراس اب تاون",
        "image": "https://img-0.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695d116ba881f218770407.jpg",
        "rooms": "2",
        "bathrooms": "2",
        "size": "160 متر²",
        "price": "60,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / ذا سيراس - كمبوند أب تاون كايرو",
        "adLink": "https://aqarmap.com.eg/ar/listing/6651080-for-rent-cairo-mokattam-compounds-uptown-cairo-the-sierras-uptown-cairo/",
        "originalAdID": null
    },
    {
        "id": 4,
        "title": "شقه 120 متر للايجار الجديد بحلميه الزيتون بالدور الثالث بعد الارضى بدون اسانسير",
        "image": "https://img-0.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695bfa5c21872139801353.png",
        "rooms": "3",
        "bathrooms": "1",
        "size": "120 متر²",
        "price": "7,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / حلمية الزيتون",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649545-for-rent-cairo-el-zaytun-hlmy-lzytwn/",
        "originalAdID": null
    },
    {
        "id": 5,
        "title": "شقه للايجار الكوم الاخضر",
        "image": "https://img-2.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c1bf7377a9202354762.jpg",
        "rooms": "3",
        "bathrooms": "1",
        "size": "140 متر²",
        "price": "3,700 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / الكوم الاخضر",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649832-for-rent-cairo-faisal-el-kom-el-akhder/",
        "originalAdID": null
    },
    {
        "id": 6,
        "title": "شقه للايجار جانبي ترسا",
        "image": "https://img-2.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c1d65b710f385506178.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "80 متر²",
        "price": "5,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع ترسا",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649851-for-rent-cairo-el-haram-el-talbya-tersa-st/",
        "originalAdID": null
    },
    {
        "id": 7,
        "title": "شقة للإيجار – 220 م – جِني كليس، شارع مرتضى عمارة حديثة – مدخل فندقي – أمن وحراس",
        "image": "https://img-0.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c1f0a06e92370198133.jpg",
        "rooms": "3",
        "bathrooms": "2",
        "size": "220 متر²",
        "price": "17,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "الاسكندرية / شارع مرتضي باشا",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649869-for-rent-alexandria-ganaklis-shr-mrtdy-bsh/",
        "originalAdID": null
    },
    {
        "id": 8,
        "title": "شقه للايجار بالمساحه",
        "image": "https://img-1.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c2d6c5f17e629335906.jpg",
        "rooms": "3",
        "bathrooms": "2",
        "size": "170 متر²",
        "price": "15,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / المساحة",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649993-for-rent-cairo-el-haram-el-msaha/",
        "originalAdID": null
    },
    {
        "id": 9,
        "title": "شقه للايجار في العروبه هرم",
        "image": "https://img-4.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695bcec864ab7359867337.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "80 متر²",
        "price": "3,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع العروبة",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649056-for-rent-cairo-el-haram-el-maryotya-el-orouba-st/",
        "originalAdID": null
    },
    {
        "id": 10,
        "title": "شقه ١٤٠ متر للايجار في حدائق القبه",
        "image": "https://img-4.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695bdd7496ab8045602817.jpg",
        "rooms": "3",
        "bathrooms": "2",
        "size": "140 متر²",
        "price": "10,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / عمارات السعودية",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649240-for-rent-cairo-hadayek-el-koba-saudi-buildings/",
        "originalAdID": null
    },
    {
        "id": 11,
        "title": "شقه للايجار العصافره شارع وهران",
        "image": "https://img-0.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695d0d8f7be9e798098477.png",
        "rooms": "2",
        "bathrooms": "1",
        "size": "100 متر²",
        "price": "8,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "الاسكندرية / العصافرة",
        "adLink": "https://aqarmap.com.eg/ar/listing/6651040-for-rent-alexandria-el-asafra/",
        "originalAdID": null
    },
    {
        "id": 12,
        "title": "شقة للايجار الجديد 100 متر",
        "image": "https://img-2.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695bea46bfd0b511631318.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "100 متر²",
        "price": "4,200 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / الطالبية",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649410-for-rent-cairo-el-haram-el-talbya/",
        "originalAdID": null
    },
    {
        "id": 13,
        "title": "*شقة للإيجار جديد بلاط* 185 متر",
        "image": "https://img-4.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695bec975e795505488158.jpg",
        "rooms": "3",
        "bathrooms": "2",
        "size": "185 متر²",
        "price": "8,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / الهرم",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649420-for-rent-cairo-el-haram/",
        "originalAdID": null
    },
    {
        "id": 14,
        "title": "شقة للإيجار في أميز مواقع شرق حلوان – شارع إسماعيل كامل",
        "image": "https://img-1.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695bf70835489601813072.jpg",
        "rooms": "3",
        "bathrooms": "1",
        "size": "150 متر²",
        "price": "7,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع اسماعيل كامل",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649511-for-rent-cairo-helwan-helwan-el-sharkeya-ismael-kamel-st/",
        "originalAdID": null
    },
    {
        "id": 15,
        "title": "شقه للايجار بالهرم بشارع الهرم الرئيسي بالمساحه",
        "image": "https://img-2.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695bf7683ce91760184036.jpg",
        "rooms": "3",
        "bathrooms": "2",
        "size": "200 متر²",
        "price": "15,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / المساحة",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649513-for-rent-cairo-el-haram-el-msaha/",
        "originalAdID": null
    },
    {
        "id": 16,
        "title": "شقه ايجار بشتيل شارع الاربعين متفرع من الحريه 90م",
        "image": "https://img-1.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cd95380378258428741.png",
        "rooms": "2",
        "bathrooms": "1",
        "size": "90 متر²",
        "price": "3,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / بشتيل",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650399-for-rent-cairo-bashtil/",
        "originalAdID": null
    },
    {
        "id": 17,
        "title": "شقة للايجار في العجمي ابو يوسف",
        "image": "https://img-3.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c31ab41592331430754.png",
        "rooms": "4",
        "bathrooms": "1",
        "size": "160 متر²",
        "price": "3,600 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "الاسكندرية / أبو يوسف",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650037-for-rent-alexandria-l-jmy-bw-ywsf/",
        "originalAdID": null
    },
    {
        "id": 18,
        "title": "شقة للايجار بالمندرة علي الملك حفني مباشرة",
        "image": "https://img-1.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695d0b30aabb4275402348.png",
        "rooms": "3",
        "bathrooms": "1",
        "size": "130 متر²",
        "price": "6,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "الاسكندرية / شارع ملك حفني",
        "adLink": "https://aqarmap.com.eg/ar/listing/6651019-for-rent-alexandria-el-mandara-shr-mlk-hfny/",
        "originalAdID": null
    },
    {
        "id": 19,
        "title": "شقة للإيجار في عمارة وحده",
        "image": "https://img-1.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695d0283d385c643533771.jpg",
        "rooms": "4",
        "bathrooms": "3",
        "size": "350 متر²",
        "price": "30,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع الجابري",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650893-for-rent-cairo-new-cairo-el-banafsg-el-banafsag-omarat-al-gabri-st/",
        "originalAdID": null
    },
    {
        "id": 20,
        "title": "شقة للايجار 100 متر في شارع عمرو بن العاص",
        "image": "https://img-2.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695b3cdeae48b782441553.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "100 متر²",
        "price": "6,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع عمرو بن العاص",
        "adLink": "https://aqarmap.com.eg/ar/listing/6647956-for-rent-cairo-faisal-el-matbeaa-amr-ibn-al-aas-st/",
        "originalAdID": null
    },
    {
        "id": 21,
        "title": "شقه للايجار ش نبيل طه",
        "image": "https://img-2.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695b4c2ee0eb4557741438.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "100 متر²",
        "price": "6,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع نبيل طه",
        "adLink": "https://aqarmap.com.eg/ar/listing/6647978-for-rent-cairo-faisal-el-matbeaa-nabeel-taha-st/",
        "originalAdID": null
    },
    {
        "id": 22,
        "title": "شقة للايجار 100 متر في شارع عمرو بن العاص",
        "image": "https://img-2.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695b3cdeae48b782441553.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "100 متر²",
        "price": "6,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع عمرو بن العاص",
        "adLink": "https://aqarmap.com.eg/ar/listing/6647956-for-rent-cairo-faisal-el-matbeaa-amr-ibn-al-aas-st/",
        "originalAdID": null
    },
    {
        "id": 23,
        "title": "شقه للايجار بسعر لقطه 100م",
        "image": "https://img-3.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695ba6496a15d420325391.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "100 متر²",
        "price": "6,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / أول فيصل",
        "adLink": "https://aqarmap.com.eg/ar/listing/6648533-for-rent-cairo-faisal-awel-faisal/",
        "originalAdID": null
    },
    {
        "id": 24,
        "title": "شقه للايجار في شارع ابوزيد الاول من العشرين فيصل",
        "image": "https://img-3.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695bcc5e46761471173232.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "80 متر²",
        "price": "3,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع العشرين",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649036-for-rent-cairo-faisal-shareaa-el-eshren/",
        "originalAdID": null
    },
    {
        "id": 25,
        "title": "دوبلكس للإيجار فى كمبوند سكاي كوندوز - فيليت",
        "image": "https://img-0.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695d09c33181e631878895.jpg",
        "rooms": "4",
        "bathrooms": "3",
        "size": "280 متر²",
        "price": "130,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / كمبوند سكاي كوندوز - فيليت",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650990-for-rent-cairo-new-cairo-compounds-villette-kmbwnd-sky-kwndwz-swdyk-villette/",
        "originalAdID": null
    },
    {
        "id": 26,
        "title": "شقه للايجار المريوطيه",
        "image": "https://img-4.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c30dd5ba9a798404740.jpg",
        "rooms": "3",
        "bathrooms": "2",
        "size": "160 متر²",
        "price": "7,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / المريوطية",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650029-for-rent-cairo-faisal-el-maryotyah/",
        "originalAdID": null
    },
    {
        "id": 27,
        "title": "شقة إيجار لقطة في قلب حلوان – سوبر لوكس 200م 3 غرف نوم ريسبشن واسع مطبخ",
        "image": "https://img-1.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c2f9050a8f490048653.png",
        "rooms": "3",
        "bathrooms": "1",
        "size": "200 متر²",
        "price": "8,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع جعفر",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650010-for-rent-cairo-helwan-helwan-el-sharkeya-gaafar-st/",
        "originalAdID": null
    },
    {
        "id": 28,
        "title": "شقة للإيجار أمام نادي طلائع الجيش – موقع مميز جدًا",
        "image": "https://img-3.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c2e422a563824433670.png",
        "rooms": "2",
        "bathrooms": "1",
        "size": "110 متر²",
        "price": "5,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / حلوان",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649998-for-rent-cairo-helwan/",
        "originalAdID": null
    },
    {
        "id": 29,
        "title": "شقه للايجار بسعر لقطه 185م",
        "image": "https://img-1.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c2e0ec741b302764289.jpg",
        "rooms": "3",
        "bathrooms": "2",
        "size": "185 متر²",
        "price": "8,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / الهرم",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649995-for-rent-cairo-el-haram/",
        "originalAdID": null
    },
    {
        "id": 30,
        "title": "شقه للإيجار الهرم 150م",
        "image": "https://img-4.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c2d1a4edbb381266884.jpg",
        "rooms": "3",
        "bathrooms": "1",
        "size": "150 متر²",
        "price": "6,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / اللبيني",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649984-for-rent-cairo-el-haram-el-lebeny/",
        "originalAdID": null
    },
    {
        "id": 31,
        "title": "شقه للايجار المريوطيه",
        "image": "https://img-2.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c276288db0145907024.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "120 متر²",
        "price": "4,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / المريوطية",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649929-for-rent-cairo-faisal-el-maryotyah/",
        "originalAdID": null
    },
    {
        "id": 32,
        "title": "شقة للايجار ١٠٠ متر في فيصل المنشية دور تاني يوجد اسانسير. الشقة غرفتين كبار",
        "image": "https://img-4.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c22cc9997a695763292.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "100 متر²",
        "price": "3,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع المنشية",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649905-for-rent-cairo-faisal-el-tawabeq-el-mansheya-st/",
        "originalAdID": null
    },
    {
        "id": 33,
        "title": "شقه للايجار بالطالبيه بجوار الجامع الكبير 80 متر",
        "image": "https://img-2.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c1b2902945153286065.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "80 متر²",
        "price": "2,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / الطالبية",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649817-for-rent-cairo-el-haram-el-talbya/",
        "originalAdID": null
    },
    {
        "id": 34,
        "title": "شقه للايجار في شارع الاربعين جسر السويس 140 متر دور 3",
        "image": "https://img-3.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c1b159200c701333793.jpg",
        "rooms": "3",
        "bathrooms": "1",
        "size": "140 متر²",
        "price": "3,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع الأربعين",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649814-for-rent-cairo-ain-shams-jsr-lswys-el-arbaeen-st/",
        "originalAdID": null
    },
    {
        "id": 35,
        "title": "شقه للايجار حدايق حلوان مدخل النخل اول شارع من كورنيش النيل",
        "image": "https://img-2.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695bf81923f9c683261292.jpg",
        "rooms": "3",
        "bathrooms": "1",
        "size": "120 متر²",
        "price": "3,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع كورنيش النيل",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649523-for-rent-cairo-helwan-hadayek-helwan-nile-corniche-st/",
        "originalAdID": null
    },
    {
        "id": 36,
        "title": "شقه للايجار بسعر لقطه 130م",
        "image": "https://img-0.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695be55c9f3ef354465992.jpg",
        "rooms": "3",
        "bathrooms": "1",
        "size": "130 متر²",
        "price": "6,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / اللبيني",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649367-for-rent-cairo-el-haram-el-lebeny/",
        "originalAdID": null
    },
    {
        "id": 37,
        "title": "شقه للايجار بسعر لقطه 80م",
        "image": "https://img-3.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695be2eb8cc35990342496.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "80 متر²",
        "price": "5,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع ترسا",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649336-for-rent-cairo-el-haram-el-talbya-tersa-st/",
        "originalAdID": null
    },
    {
        "id": 38,
        "title": "شقه للايجار ش نبيل طه",
        "image": "https://img-2.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695b4c2ee0eb4557741438.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "100 متر²",
        "price": "6,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع نبيل طه",
        "adLink": "https://aqarmap.com.eg/ar/listing/6647978-for-rent-cairo-faisal-el-matbeaa-nabeel-taha-st/",
        "originalAdID": null
    },
    {
        "id": 39,
        "title": "شقة مميزة للإيجار – حلوان / شارع شريف 160م 3 غرف نوم واسعة 2 حمام ريسبشن كبير",
        "image": "https://img-0.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695c2e886f52e580028186.png",
        "rooms": "3",
        "bathrooms": "2",
        "size": "160 متر²",
        "price": "8,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع شريف",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649999-for-rent-cairo-helwan-sherif-st/",
        "originalAdID": null
    },
    {
        "id": 40,
        "title": "شقه للايجار في حلوان شارع رياض",
        "image": "https://img-3.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695bdfde46be5862302387.jpg",
        "rooms": "3",
        "bathrooms": "2",
        "size": "150 متر²",
        "price": "8,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع رياض باشا",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649281-for-rent-cairo-helwan-helwan-el-sharkeya-ryad-pasha-st/",
        "originalAdID": null
    },
    {
        "id": 41,
        "title": "شقه للايجار في قلب حلوان: شارع جعفر موقع حيوي وقريب من كل الخدمات",
        "image": "https://img-4.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695bdd8f348b8513492400.jpg",
        "rooms": "3",
        "bathrooms": "1",
        "size": "200 متر²",
        "price": "8,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع جعفر",
        "adLink": "https://aqarmap.com.eg/ar/listing/6649238-for-rent-cairo-helwan-helwan-el-sharkeya-gaafar-st/",
        "originalAdID": null
    },
{
        "id": 22,
        "title": "شقة 207م للايجار نص مفروش في هايد بارك",
        "image": "https://img-1.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695d018477fa7051597014.jpg",
        "rooms": "3",
        "bathrooms": "3",
        "size": "207 متر²",
        "price": "45,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / اتش بي ار - كمبوند هايد بارك",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650880-for-rent-cairo-new-cairo-compounds-hyde-park-hpr-hyde-park/",
        "originalAdID": null
    },
    {
        "id": 23,
        "title": "شقة فاخرة للإيجار فى سبيكترام - كمبوند ايست تاون",
        "image": "https://img-2.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695d00696eab8739778901.jpg",
        "rooms": "2",
        "bathrooms": "3",
        "size": "156 متر²",
        "price": "70,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / سبيكترام - كمبوند ايست تاون",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650862-for-rent-cairo-new-cairo-compounds-eastown-spectrum-eastown-compound/",
        "originalAdID": null
    },
    {
        "id": 24,
        "title": "شقه للايجار فاضيه في النرجس الجديده",
        "image": "https://img-3.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cf4d345cc1148415602.jpg",
        "rooms": "3",
        "bathrooms": "2",
        "size": "175 متر²",
        "price": "20,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / النرجس الجديدة",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650714-for-rent-cairo-new-cairo-new-narges/",
        "originalAdID": null
    },
    {
        "id": 25,
        "title": "دور كامل إداري للإيجار على محور محمد نجيب – مساحة 1,600 م²",
        "image": "https://img-4.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cfffc3ef5c223237057.jpg",
        "rooms": "1",
        "bathrooms": "1",
        "size": "1600 متر²",
        "price": "3,200,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / محور محمد نجيب",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650820-for-rent-cairo-new-cairo-mohammed-nagib-axis-st/",
        "originalAdID": null
    },
    {
        "id": 26,
        "title": "ستوديو للايجار مفروش بابراج زيد الشيخ زايد",
        "image": "https://img-0.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cfe203f14c272614095.jpg",
        "rooms": "1",
        "bathrooms": "1",
        "size": "60 متر²",
        "price": "40,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / زد تاور - كمبوند زيد الشيخ زايد",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650845-for-rent-cairo-el-sheikh-zayed-city-compounds-zyd-wr-llttwyr-z-tower/",
        "originalAdID": null
    },
    {
        "id": 27,
        "title": "شقة للإيجار الجديد– 220 متر موقع مميز – شارع النزهه ، مدينه نصر",
        "image": "https://img-1.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cebb6c9c05797762538.jpg",
        "rooms": "3",
        "bathrooms": "2",
        "size": "220 متر²",
        "price": "22,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع النزهة",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650593-for-rent-cairo-heliopolis-shareaa-el-nozha/",
        "originalAdID": null
    },
    {
        "id": 28,
        "title": "شقة 155م سوبر لوكس للإيجار في كمبوند باراديس، التجمع الخامس",
        "image": "https://img-0.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cfb43dfb7f274948572.jpg",
        "rooms": "3",
        "bathrooms": "2",
        "size": "155 متر²",
        "price": "20,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / كمبوند باراديس - المهندسين",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650792-for-rent-cairo-new-cairo-compounds-paradise/",
        "originalAdID": null
    },
    {
        "id": 29,
        "title": "شقه للايجار200م التراسوبرلوكس فى الحى الاول التجمع الخامس كودL3952",
        "image": "https://img-3.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cf81dd4fd7496546210.jpg",
        "rooms": "3",
        "bathrooms": "3",
        "size": "200 متر²",
        "price": "27,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع رقم.7",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650758-for-rent-cairo-new-cairo-el-ahyaa-first-neighborhood-no-7/",
        "originalAdID": null
    },
    {
        "id": 30,
        "title": "شقة للايجار ١٠٠ متر في فيصل المنشية دور تاني يوجد اسانسير. الشقة غرفتين كبار وري",
        "image": "https://img-0.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/6959680356135477856600.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "100 متر²",
        "price": "3,500 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع المنشية",
        "adLink": "https://aqarmap.com.eg/ar/listing/6644786-for-rent-cairo-faisal-el-tawabeq-el-mansheya-st/",
        "originalAdID": null
    },
    {
        "id": 31,
        "title": "شقة للإيجار210م في السياحيه الاولي خلف واحة خطاب خطوات لوصلة دهشور?✨",
        "image": "https://img-3.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cf5851a480025376985.jpg",
        "rooms": "3",
        "bathrooms": "3",
        "size": "210 متر²",
        "price": "25,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / طريق وصلة دهشور",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650729-for-rent-cairo-6th-of-october-tryq-wsl-dhshwr/",
        "originalAdID": null
    },
    {
        "id": 32,
        "title": "شقه للايجار جسر السويس",
        "image": "https://img-3.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cf45a5977b461992693.jpg",
        "rooms": "3",
        "bathrooms": "2",
        "size": "150 متر²",
        "price": "5,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع جسر السويس",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650712-for-rent-cairo-nozha-2-gesr-el-suez-st/",
        "originalAdID": null
    },
    {
        "id": 33,
        "title": "شقه للايجار تالت نمره من شارع الاربعين خلف حديقه بدر النزهه 2",
        "image": "https://img-3.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cf339b9d4a928855398.jpg",
        "rooms": "3",
        "bathrooms": "2",
        "size": "130 متر²",
        "price": "4,700 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع جسر السويس",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650686-for-rent-cairo-nozha-2-gesr-el-suez-st/",
        "originalAdID": null
    },
    {
        "id": 34,
        "title": "شقة للايجار 220 م في سوليك ( سموحة ) - بيتك في النادي",
        "image": "https://img-4.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695ce925bcfbc146946794.jpg",
        "rooms": "3",
        "bathrooms": "2",
        "size": "220 متر²",
        "price": "38,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "الاسكندرية / شارع النقل والهندسة بسموحة",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650571-for-rent-alexandria-smouha-shr-lnql-wlhnds-bsmwh/",
        "originalAdID": null
    },
    {
        "id": 35,
        "title": "شقه للايجار سوبر لوكس في ليك فيو ريزيدنس التجمع الخامس",
        "image": "https://img-0.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cf05196984162035732.jpg",
        "rooms": "2",
        "bathrooms": "2",
        "size": "130 متر²",
        "price": "50,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / ليك فيو ريزيدنس - الحاذق",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650648-for-rent-cairo-new-cairo-compounds-lakeview-residence/",
        "originalAdID": null
    },
    {
        "id": 36,
        "title": "ستوديو مفروش للايجار ب فيلدج جيت",
        "image": "https://img-0.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695ceec016900560842330.jpg",
        "rooms": "1",
        "bathrooms": "1",
        "size": "88 متر²",
        "price": "62,400 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / كمبوند فيلدج جيت - بالم هيلز",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650633-for-rent-cairo-new-cairo-compounds-kmbwnd-fyldj-jyt-blm-hylz/",
        "originalAdID": null
    },
    {
        "id": 37,
        "title": "شقة 250م للإيجار قانون جديد – مدينة نصر-الحي العاشر – موقع متميز جدًا",
        "image": "https://img-0.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cefa2eaf79898790897.jpg",
        "rooms": "4",
        "bathrooms": "2",
        "size": "250 متر²",
        "price": "30,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / الحي العاشر",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650644-for-rent-cairo-nasr-city-el-hay-el-asher/",
        "originalAdID": null
    },
    {
        "id": 38,
        "title": "شقه للايجار 140متر خامس نمره من شارع 27 النزهه 2",
        "image": "https://img-3.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cf13b1d698052877862.png",
        "rooms": "3",
        "bathrooms": "2",
        "size": "140 متر²",
        "price": "6,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع 27",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650666-for-rent-cairo-elnozha-Streettt-27/",
        "originalAdID": null
    },
    {
        "id": 39,
        "title": "Apartments For rent in Azad Compound - Tameer",
        "image": "https://img-4.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cee4631d9b538183070.jpg",
        "rooms": "2",
        "bathrooms": "2",
        "size": "150 متر²",
        "price": "70,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / كمبوند أزاد - تعمير",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650623-for-rent-cairo-new-cairo-compounds-azad/",
        "originalAdID": null
    },
    {
        "id": 40,
        "title": "شقة 180م بالمطبخ للإيجار في كمبوند لاميرادا",
        "image": "https://img-4.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695cefd73227b802233745.jpg",
        "rooms": "3",
        "bathrooms": "3",
        "size": "180 متر²",
        "price": "28,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / كمبوند لا ميرادا - جراند بلازا",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650647-for-rent-cairo-new-cairo-lmstqbl-syty-compounds-kmbwnd-l-myrd-lmstqbl/",
        "originalAdID": null
    },
    {
        "id": 41,
        "title": "شقة للإيجار الجديد– 150 متر موقع مميز – المريلاند ، مصر الجديدة",
        "image": "https://img-1.aqarmap.com.eg/new-aqarmap-media/search-thumb-webp/2601/695ce59177a7f138958973.jpg",
        "rooms": "2",
        "bathrooms": "1",
        "size": "150 متر²",
        "price": "26,000 جنيه",
        "currency": "EGP",
        "type": "rent",
        "area": "القاهرة الكبرى / شارع المعهد الاشتراكي",
        "adLink": "https://aqarmap.com.eg/ar/listing/6650487-for-rent-cairo-heliopolis-merryland-el-maahad-eshtraki-st/",
        "originalAdID": null
    }
]
export default data


